from __future__ import annotations

import json
import os
import re
import time
from typing import Any

from google import genai
from google.genai import types

from gemini_analyzer import DEFAULT_MODEL, FALLBACK_MODEL


VERTEX_MODELS = (
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-3.6-flash",
)


def _build_client(
    api_key: str | None = None,
):
    project = (
        os.getenv("GOOGLE_CLOUD_PROJECT")
        or os.getenv("PROJECT_ID")
        or ""
    ).strip()
    location = (
        os.getenv("GOOGLE_CLOUD_LOCATION")
        or "global"
    ).strip()

    if project:
        return (
            genai.Client(
                vertexai=True,
                project=project,
                location=location,
            ),
            "vertex-ai",
        )

    if api_key:
        return (
            genai.Client(api_key=api_key),
            "developer-api",
        )

    raise RuntimeError(
        "Gemini authentication is not configured."
    )


def _candidate_models(
    requested: str | None,
) -> list[str]:
    models: list[str] = []
    for candidate in (
        *VERTEX_MODELS,
        requested or "",
        FALLBACK_MODEL,
    ):
        if candidate and candidate not in models:
            models.append(candidate)
    return models


def _is_retryable(exc: Exception) -> bool:
    text = str(exc).upper()
    return any(
        token in text
        for token in (
            "429",
            "503",
            "UNAVAILABLE",
            "RESOURCE_EXHAUSTED",
            "TIMEOUT",
        )
    )


def _normalize_device_piv_wording(text: str) -> str:
    value=str(text or "")
    device_patterns=(
        "PC",
        "PC User",
        "iPhone",
        "Sony Xperia",
        "Google Pixel",
        "Galaxy",
        "Galaxy S",
        "Galaxy Z",
        "Galaxy A",
    )

    # Device segments mean PIV generated by users browsing from those devices.
    # Normalize misleading expressions such as "PCのPIV".
    for device in sorted(
        device_patterns,
        key=len,
        reverse=True,
    ):
        value=re.sub(
            rf"{re.escape(device)}のPIV",
            f"{device}ユーザーからのPIV",
            value,
        )

    # Also normalize combined expressions such as
    # "PC・Sony XperiaのPIV".
    value=re.sub(
        r"((?:PC|PC User|iPhone|Sony Xperia|Google Pixel|Galaxy(?: [SZA])?)"
        r"(?:・(?:PC|PC User|iPhone|Sony Xperia|Google Pixel|Galaxy(?: [SZA])?))+)"
        r"のPIV",
        r"\1ユーザーからのPIV",
        value,
    )
    return value


def _change_rate(current: float, previous: float) -> float | None:
    if not previous:
        return None
    return (
        (float(current) - float(previous))
        / float(previous)
        * 100
    )


def _fallback_headline(product: dict[str, Any]) -> str:
    total = product.get("main", {}).get("Total", {})
    current = total.get("current", {})
    previous = total.get("previous", {})
    older = total.get("older", {})

    current_pd = int(current.get("pd_visit", 0) or 0)
    previous_pd = int(previous.get("pd_visit", 0) or 0)
    older_pd = int(older.get("pd_visit", 0) or 0)

    vs_previous = _change_rate(current_pd, previous_pd)
    vs_older = _change_rate(current_pd, older_pd)

    if vs_previous is not None and vs_previous < 0:
        if vs_older is not None and abs(vs_older) <= 10:
            return "PD Visitは前週比減も先々週水準"
        if vs_older is not None and vs_older < 0:
            return "PD Visitは2週連続で減少"
        if vs_older is not None:
            return "PD Visitは前週比減、先々週比では増加"
        return "PD Visitは前週比で減少"

    if vs_previous is not None and vs_previous > 0:
        if vs_older is not None and vs_older > 0:
            return "PD Visitは先週・先々週を上回る水準"
        return "PD Visitは前週比で増加"

    return "PD Visitは前週並み"


def _daily_summary(product: dict[str, Any]) -> dict[str, Any]:
    daily = product.get("piv_detail", {}).get("daily", {})
    result: dict[str, Any] = {}

    for period in ("older", "previous", "current"):
        rows = daily.get(period, [])
        if not rows:
            continue

        visits = [
            int(row.get("visits", 0) or 0)
            for row in rows
        ]
        if not visits:
            continue

        max_index = max(
            range(len(visits)),
            key=lambda index: visits[index],
        )
        min_index = min(
            range(len(visits)),
            key=lambda index: visits[index],
        )
        result[period] = {
            "days": rows,
            "average_visits": sum(visits) / len(visits),
            "max_day": rows[max_index],
            "min_day": rows[min_index],
        }

    return result


def build_analysis_payload(product: dict[str, Any]) -> dict[str, Any]:
    return {
        "product": product.get("product_name", ""),
        "url": product.get("url", ""),
        "period_dates": product.get("period_dates", {}),
        "main_metrics": product.get("main", {}),
        "device_mix": product.get("device_summary", {}),
        "device_ranking_current": product.get("device_ranking", []),
        "piv_detail": product.get("piv_detail", {}),
        "daily_summary": _daily_summary(product),
        "purchase_funnel": product.get("funnel", {}),
    }


def _grounding_sources(response) -> list[dict[str, str]]:
    sources: list[dict[str, str]] = []

    try:
        candidates = getattr(response, "candidates", None) or []
        if not candidates:
            return sources

        metadata = getattr(
            candidates[0],
            "grounding_metadata",
            None,
        )
        chunks = getattr(
            metadata,
            "grounding_chunks",
            None,
        ) or []

        for chunk in chunks:
            web = getattr(chunk, "web", None)
            if not web:
                continue

            title = str(
                getattr(web, "title", "") or ""
            ).strip()
            uri = str(
                getattr(web, "uri", "") or ""
            ).strip()

            if not uri:
                continue

            item = {
                "title": title,
                "url": uri,
            }
            if item not in sources:
                sources.append(item)
    except Exception:
        return sources

    return sources[:8]


def research_market_context(
    *,
    api_key: str | None,
    start_date: str,
    end_date: str,
    model: str = DEFAULT_MODEL,
) -> dict[str, Any]:
    client, backend = _build_client(api_key)

    prompt = f"""
日本のスマートフォンECトラフィックの週次分析に使うため、
{start_date} から {end_date} の期間について、次の事実をGoogle検索で確認してください。

対象:
- Samsung Japan / Galaxy / Samsung.comの大型キャンペーン、Samsung Week、セール、クーポン、予約・発売、主要販促
- docomo、au、SoftBank、Rakuten、J:COMなどキャリア側のGalaxy関連キャンペーン
- Apple / iPhone、Google Pixel、Sony Xperia、Xiaomi、OPPOなど主要競合の日本向け発表・予約・発売
- 日本の祝日、大型連休、シルバーウィーク、連休の谷間などECトラフィックに影響し得るカレンダー要因

条件:
- 日付を確認できる事実だけを書く。
- Samsung公式、キャリア公式、メーカー公式、主要メディアなど信頼できる情報を優先する。
- 開始日 / 終了日 / 発表日 / 発売日が分析期間のどこに入るか分かるようにする。
- 一般論や推測は書かない。
- この段階ではトラフィック増減の原因だと断定しない。分析モデル側でCSVとの整合を確認する。
- 該当事項がなければ「特記事項なし」とする。
- 500文字以内の簡潔な箇条書きにする。
""".strip()

    last_error: Exception | None = None

    for candidate in _candidate_models(model):
        for delay in (0, 2):
            if delay:
                time.sleep(delay)

            try:
                response = client.models.generate_content(
                    model=candidate,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        tools=[
                            types.Tool(
                                google_search=types.GoogleSearch()
                            )
                        ],
                        temperature=0.0,
                        max_output_tokens=600,
                    ),
                )

                text = str(response.text or "").strip()
                if not text:
                    raise RuntimeError(
                        "Gemini market context was empty"
                    )

                return {
                    "text": text,
                    "sources": _grounding_sources(response),
                    "model": candidate,
                    "backend": backend,
                }
            except Exception as exc:
                last_error = exc
                if not _is_retryable(exc):
                    break

    return {
        "text": "",
        "sources": [],
        "model": "none",
        "backend": backend,
        "error": str(last_error) if last_error else "",
    }


def _parse_json_text(text: str) -> dict[str, Any]:
    cleaned = (text or "").strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(
            r"^```(?:json)?\s*",
            "",
            cleaned,
        )
        cleaned = re.sub(
            r"\s*```$",
            "",
            cleaned,
        )

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(
            r"\{.*\}",
            cleaned,
            flags=re.S,
        )
        if not match:
            raise
        return json.loads(match.group(0))


def generate_pd_bc_insight(
    *,
    product: dict[str, Any],
    api_key: str | None,
    market_context: dict[str, Any] | None = None,
    model: str = DEFAULT_MODEL,
) -> dict[str, Any]:
    payload = build_analysis_payload(product)
    payload["market_context"] = market_context or {}

    client, backend = _build_client(api_key)

    system_prompt = """
あなたはSamsung Japan向けPD+BC Page週次レポートのWebアナリストです。
入力されたAdobe Analyticsデータと、別途Google検索で確認済みのmarket_contextだけを根拠に、
PowerPoint上部の短い分析コメントを作成してください。

必ず次のJSONだけを返してください。
{
  "headline_comment": "スライド上部の青字に入れる短い分析文",
  "detail_comment": "プレビュー用の補足分析"
}

分析ルール:
- older=先々週、previous=先週、current=今週として3週トレンドを見る。
- 今週が先週より減少していても、先々週と同水準なら「先々週水準」など3週比較を優先する。
- Totalだけでなく、Channel別PD/BC Visit、PIV/PIR、購入経路も比較する。
- PIV詳細、キャリア別PIV、eStore PIV、日別Visit/PIVを必ず確認する。
- 端末別はGalaxy/iPhone/Sony固定ではなく、currentのPIV量・構成比・PIR・変化が目立つ端末を選ぶ。
- Google PixelやPC Userが重要ならSony Xperiaより優先する。
- 端末別セグメントのPIVは、その端末そのもののPIVではなく「その端末を利用してアクセスしたユーザーからのPIV」を意味する。
- したがって「PCのPIV」「Sony XperiaのPIV」のように書かず、「PCユーザーからのPIV」「Sony XperiaユーザーからのPIV」と表現する。
- 複数端末をまとめる場合も「PC・Sony XperiaユーザーからのPIV」のように書く。
- 日別データから祝日・連休・イベント日に対応する山谷が見える場合は、週次Totalより優先して解釈に使う。
- market_contextにある外部イベントとCSVの動きが一致する場合は、「原因候補」として一歩踏み込んだ仮説を出してよい。
- ただし外部イベントだけで因果を決めず、必ず対応するCSV指標をセットで確認する。
- 例:
  1) シルバーウィーク期間にDaily Visitが上昇し、終了後に低下している
     → 「シルバーウィーク中に高まったVisitが、連休明けに通常水準へ戻った可能性」
  2) iPhoneの発表・発売週に、対象Galaxy製品のiPhone UserのVisit / PIV / PIRが先週・先々週より増えている
     → 「iPhone新製品を契機にスマホ関心が高まり、iPhoneユーザーの比較検討流入が増えた可能性」
  3) Samsung WeekやSamsung.comキャンペーン期間にeStore PIV、Carrier PIV、PIR、Paid / CRM / Directなど関連指標が上昇
     → 「SamsungキャンペーンがPIR上昇の一因となった可能性」
- こうした仮説を出す場合、detail_commentでは「どのイベント」と「どのCSV指標」が対応しているか分かるようにする。
- イベントと指標のタイミングが合わない、または該当指標が動いていない場合はイベントを原因候補にしない。
- market_contextにない外部イベントを新しく作らない。
- 数値にない広告配信変更やキャンペーン要因を推測しない。
- 「〜の影響で」と断定するより、「〜が背景の一因の可能性」「〜を契機に増えた可能性」を優先する。
- headline_commentは最大70文字。最重要ポイントを1〜2個に絞る。
- 外部イベントとCSVの動きが強く整合する場合は、単なる「増減」より背景仮説を優先してheadlineに採用してよい。
- detail_commentは最大160文字。3週比較、端末構成、日別、外部イベントのうち、
  headlineに入らなかった有用な補足を1文でまとめる。
- 「と思われる」「〜のはず」は使わない。
""".strip()

    last_error: Exception | None = None

    for candidate in _candidate_models(model):
        for delay in (0, 2):
            if delay:
                time.sleep(delay)

            try:
                response = client.models.generate_content(
                    model=candidate,
                    contents=json.dumps(
                        payload,
                        ensure_ascii=False,
                    ),
                    config=types.GenerateContentConfig(
                        system_instruction=system_prompt,
                        temperature=0.1,
                        max_output_tokens=450,
                        response_mime_type="application/json",
                    ),
                )

                data = _parse_json_text(
                    response.text or "{}"
                )

                headline = _normalize_device_piv_wording(
                    str(
                        data.get("headline_comment", "")
                        or ""
                    ).strip()
                )
                detail = _normalize_device_piv_wording(
                    str(
                        data.get("detail_comment", "")
                        or ""
                    ).strip()
                )

                if not headline:
                    raise RuntimeError(
                        "Gemini headline_comment was empty"
                    )

                return {
                    "headline_comment": headline,
                    "detail_comment": detail,
                    "model": candidate,
                    "backend": backend,
                    "market_context": market_context or {},
                }
            except Exception as exc:
                last_error = exc
                if not _is_retryable(exc):
                    break

    return {
        "headline_comment": _fallback_headline(product),
        "detail_comment": "",
        "model": "fallback",
        "backend": backend,
        "market_context": market_context or {},
        "error": str(last_error) if last_error else "",
    }


def fallback_pd_bc_insight(
    product: dict[str, Any],
) -> dict[str, Any]:
    return {
        "headline_comment": _fallback_headline(product),
        "detail_comment": "",
        "model": "fallback",
        "market_context": {},
    }
